### ISSUE TITLE
Making the subject index

### ISSUE THREAD

**Issue by itamarkast** [langsci/271#621]
Some of the subjects in the subject index are ordered wrong, e.g. *\emph{by itself}* which is placed at the beginning of the index (because `\` is ordered before alphanumeric characters).
A small script fixes this by creating a new sdx file in step 2 of the index-building process:
1. Compile the book as usual (to generate `main.sdx`).
2. `perl scripts/fix_main_sdx.pl main.sdx <name_of_file>`
3. `makeindex -i main.snd <name_of_file>`
4. Compile the book as usual.

**Comment by kopeckyf** [comment]
This can be achieved with on-board index features, see: https://en.wikibooks.org/wiki/LaTeX/Indexing#Sophisticated_indexing
